"""LittleBoy adversarial calibration corpus & golden-file regression (v0.9).

A labelled corpus of adversarial and clean cases, run through the audit, scored
into a miss rate and a false-alarm rate, and pinned by golden-file regression so
that drift in the audit's behaviour is caught and the false-alarm/miss trade-off
can be tuned deliberately.
"""

from __future__ import annotations

from littleboy.calibration.corpus import (
    default_corpus,
    golden_payload,
    load_corpus,
    run_corpus,
)
from littleboy.calibration.diagnosis import (
    diagnose_disagreements,
    diagnosis_golden_payload,
)
from littleboy.calibration.explain import (
    explain_label_disagreement,
    explain_policy_disagreement,
    explain_reliability_disagreements,
    explanation_golden_payload,
    minimal_fact_accounts,
    minimal_policy_accounts,
)
from littleboy.calibration.fitting import (
    cross_validate_threshold_policy,
    cross_validated_fit_golden_payload,
    cv_gain_inference,
    cv_gain_inference_golden_payload,
    fit_threshold_policy,
    fitted_policy_golden_payload,
)
from littleboy.calibration.generator import (
    default_generated_scoring_corpus,
    default_labelled_outcome_corpus,
    external_case_bank,
    generate_outcome_corpus,
    generate_scoring_corpus,
)
from littleboy.calibration.labels import (
    apply_labels,
    consensus_verdict,
    labels_to_csv,
    outcome_corpus_from_csv,
    parse_labels_csv,
    parse_verdict,
)
from littleboy.calibration.metrics import aggregate, score_entry
from littleboy.calibration.models import (
    AuditCorpus,
    CalibrationOutcome,
    CalibrationReport,
    CaseDigest,
    CaseFlip,
    ConfidenceInterval,
    CorpusEntry,
    CrossValidatedFit,
    CVGainInference,
    DiagnosisFraction,
    DisagreementDiagnosis,
    DisagreementExplanation,
    FittedPolicy,
    FoldResult,
    GoldenImpact,
    InterRaterAgreement,
    LabelerVerdict,
    LayerExpectation,
    LayerMetrics,
    OutcomeCorpus,
    OutcomeEntry,
    PolicyRecommendation,
    PolicyReliability,
    PolicyScoringMetrics,
    RecurringAccount,
    ReliabilityReport,
    ScoringCalibrationReport,
    ScoringCorpus,
    ScoringCorpusEntry,
    SplitReliability,
    StakeholderImpact,
    ThresholdFlip,
    ThresholdSet,
    TraceDelta,
    TuningImpact,
)
from littleboy.calibration.reliability import (
    default_external_outcome_corpus,
    default_independent_outcome_corpus,
    default_outcome_corpus,
    disposition,
    inter_rater_agreement,
    load_outcome_corpus,
    recommend_policy,
    recommend_policy_for_stakeholder,
    reliability_golden_payload,
    run_reliability,
)
from littleboy.calibration.scoring import (
    default_scoring_corpus,
    load_scoring_corpus,
    run_scoring_corpus,
    scoring_golden_payload,
    wilson_ci,
)
from littleboy.calibration.tuner import (
    candidate_profile,
    tune_dry_run,
    tuning_golden_payload,
)

__all__ = [
    "AuditCorpus",
    "CalibrationOutcome",
    "CalibrationReport",
    "CaseDigest",
    "CaseFlip",
    "ConfidenceInterval",
    "CorpusEntry",
    "CrossValidatedFit",
    "CVGainInference",
    "DiagnosisFraction",
    "DisagreementDiagnosis",
    "DisagreementExplanation",
    "FittedPolicy",
    "FoldResult",
    "GoldenImpact",
    "InterRaterAgreement",
    "LabelerVerdict",
    "LayerExpectation",
    "LayerMetrics",
    "OutcomeCorpus",
    "OutcomeEntry",
    "PolicyRecommendation",
    "PolicyReliability",
    "PolicyScoringMetrics",
    "RecurringAccount",
    "ReliabilityReport",
    "ScoringCalibrationReport",
    "ScoringCorpus",
    "ScoringCorpusEntry",
    "SplitReliability",
    "StakeholderImpact",
    "ThresholdFlip",
    "ThresholdSet",
    "TraceDelta",
    "TuningImpact",
    "aggregate",
    "apply_labels",
    "candidate_profile",
    "consensus_verdict",
    "cross_validate_threshold_policy",
    "cross_validated_fit_golden_payload",
    "cv_gain_inference",
    "cv_gain_inference_golden_payload",
    "default_corpus",
    "default_external_outcome_corpus",
    "default_generated_scoring_corpus",
    "default_independent_outcome_corpus",
    "default_labelled_outcome_corpus",
    "default_outcome_corpus",
    "default_scoring_corpus",
    "diagnose_disagreements",
    "diagnosis_golden_payload",
    "disposition",
    "explain_label_disagreement",
    "explain_policy_disagreement",
    "explain_reliability_disagreements",
    "explanation_golden_payload",
    "external_case_bank",
    "fit_threshold_policy",
    "fitted_policy_golden_payload",
    "generate_outcome_corpus",
    "generate_scoring_corpus",
    "golden_payload",
    "inter_rater_agreement",
    "labels_to_csv",
    "load_corpus",
    "load_outcome_corpus",
    "load_scoring_corpus",
    "minimal_fact_accounts",
    "minimal_policy_accounts",
    "outcome_corpus_from_csv",
    "parse_labels_csv",
    "parse_verdict",
    "recommend_policy",
    "recommend_policy_for_stakeholder",
    "reliability_golden_payload",
    "run_corpus",
    "run_reliability",
    "run_scoring_corpus",
    "score_entry",
    "scoring_golden_payload",
    "tune_dry_run",
    "tuning_golden_payload",
    "wilson_ci",
]
