"""LittleBoy: a rational ethical evaluation engine.

Foundational axiom:

    The fundamental ethical evil is coercion.
    The ethical good is the minimization or absence of coercion.

This package is an early, deliberately small foundation. It is a transparent
reasoning engine, not an oracle: it always reports its uncertainty, the data it
is missing, and the axioms it invoked. It is NOT a legal, medical, or emergency
decision-maker.
"""

from __future__ import annotations

from littleboy.audit import (
    AdversarialRiskProfile,
    AdversarialStressTester,
    AuditCategory,
    AuditFinding,
    AuditReport,
    AuditSeverity,
    BiasProfile,
    ComparisonAuditReport,
    StressTestResult,
)
from littleboy.calibration import (
    AuditCorpus,
    CalibrationReport,
    CorpusEntry,
    FittedPolicy,
    InterRaterAgreement,
    OutcomeCorpus,
    PolicyRecommendation,
    ReliabilityReport,
    ScoringCalibrationReport,
    ScoringCorpus,
    ThresholdSet,
    default_corpus,
    default_labelled_outcome_corpus,
    default_outcome_corpus,
    default_scoring_corpus,
    fit_threshold_policy,
    generate_outcome_corpus,
    generate_scoring_corpus,
    labels_to_csv,
    outcome_corpus_from_csv,
    parse_labels_csv,
    recommend_policy,
    recommend_policy_for_stakeholder,
    run_corpus,
    run_reliability,
    run_scoring_corpus,
)
from littleboy.case_builder import (
    CaseBuilder,
    ScenarioTemplate,
    build_case_from_answers,
    completeness_report,
    generate_questions,
    get_template,
    list_templates,
    wizard_prompts,
)
from littleboy.comparison import (
    ActionComparisonResult,
    ActionComparisonSet,
    ActionOption,
    ActionRankingEntry,
    ComparisonEngine,
    DominanceResult,
    TradeoffAnalysis,
    compare,
)
from littleboy.core.agency import assess_agency, assess_consent
from littleboy.core.alternatives import analyse_alternatives
from littleboy.core.axioms import (
    agent_can_bear_duties,
    evaluate_coercion_justification,
)
from littleboy.core.enums import (
    AgentType,
    ConsentStatus,
    EpistemicStatus,
    LanguageMedium,
    PolicyMode,
    QuestionCategory,
    QuestionPriority,
    RuleResultStatus,
    RuleSeverity,
    SourceType,
    TimeHorizon,
    UncertaintyLevel,
    Verdict,
)
from littleboy.core.evaluator import EthicalEvaluator
from littleboy.core.gates import (
    detect_missing_critical_data,
    recommended_next_questions,
)
from littleboy.core.models import (
    ActionCase,
    AgencyProfile,
    Alternative,
    AlternativeAction,
    AlternativeAnalysis,
    AlternativeSet,
    CaseCompletenessReport,
    CoercionJustification,
    CoercionProfile,
    ConsentProfile,
    DataQualityProfile,
    EvaluationReport,
    ExperimentSummary,
    IntakeHints,
    JustificationResult,
    MoralAgent,
    Question,
    QuestionSet,
    ReasoningTrace,
    RuleResult,
)
from littleboy.data.evidence import EvidenceItem, EvidenceSet
from littleboy.deliberation import (
    ComparisonDeliberationReport,
    DeliberationReport,
    Deliberator,
    InformationValue,
    IntakeTranscript,
    MinimalFlipSet,
    MinimalQuestionPlan,
    cheapest_flip_set,
    comparison_value_of_information,
    expected_cost_first_question,
    expected_questionnaire_cost,
    minimal_flip_sets,
    plan_minimal_questions,
    run_minimal_intake,
    value_of_information,
)
from littleboy.language import (
    ConstructiveLanguageAssessment,
    LanguageAct,
    LanguageAnalysis,
    LanguageContext,
    LanguageEthicsProfile,
    ManipulationFinding,
    analyze_language,
    detect_manipulation,
    score_constructive_language,
    score_language_ethics,
    score_linguistic_coercion,
)
from littleboy.reasoning.experiment import EthicalExperiment, EthicalExperimentResult
from littleboy.rules import (
    BUILTIN_RULES,
    PolicyProfile,
    Rule,
    RuleEngine,
    RuleRegistry,
    default_registry,
    get_policy,
)
from littleboy.temporal import (
    ConsequenceEstimate,
    ConsequenceSet,
    CumulativeCoercionProfile,
    ReversibilityProfile,
    TemporalConsequenceReport,
    TemporalPhase,
    TemporalProfile,
    TemporalProjection,
    TemporalProjectionResult,
    assess_consequences,
    project_temporal,
    score_cumulative_coercion,
    score_reversibility,
)

__version__ = "0.15.0"

__all__ = [
    "AuditCorpus",
    "CalibrationReport",
    "ComparisonDeliberationReport",
    "CorpusEntry",
    "DeliberationReport",
    "Deliberator",
    "FittedPolicy",
    "InformationValue",
    "IntakeHints",
    "IntakeTranscript",
    "InterRaterAgreement",
    "MinimalFlipSet",
    "MinimalQuestionPlan",
    "OutcomeCorpus",
    "PolicyRecommendation",
    "ReliabilityReport",
    "ScoringCalibrationReport",
    "ScoringCorpus",
    "ThresholdSet",
    "cheapest_flip_set",
    "comparison_value_of_information",
    "default_corpus",
    "default_labelled_outcome_corpus",
    "default_outcome_corpus",
    "default_scoring_corpus",
    "expected_cost_first_question",
    "expected_questionnaire_cost",
    "fit_threshold_policy",
    "generate_outcome_corpus",
    "generate_scoring_corpus",
    "labels_to_csv",
    "minimal_flip_sets",
    "outcome_corpus_from_csv",
    "parse_labels_csv",
    "plan_minimal_questions",
    "recommend_policy",
    "recommend_policy_for_stakeholder",
    "run_corpus",
    "run_minimal_intake",
    "run_reliability",
    "run_scoring_corpus",
    "value_of_information",
    "BUILTIN_RULES",
    "ActionCase",
    "ActionComparisonResult",
    "ActionComparisonSet",
    "ActionOption",
    "ActionRankingEntry",
    "AdversarialRiskProfile",
    "AdversarialStressTester",
    "AgencyProfile",
    "AgentType",
    "AuditCategory",
    "AuditFinding",
    "AuditReport",
    "AuditSeverity",
    "BiasProfile",
    "ComparisonAuditReport",
    "StressTestResult",
    "Alternative",
    "AlternativeAction",
    "AlternativeAnalysis",
    "AlternativeSet",
    "CaseBuilder",
    "CaseCompletenessReport",
    "CoercionJustification",
    "ConstructiveLanguageAssessment",
    "CoercionProfile",
    "ComparisonEngine",
    "ConsentProfile",
    "ConsentStatus",
    "ConsequenceEstimate",
    "ConsequenceSet",
    "CumulativeCoercionProfile",
    "DataQualityProfile",
    "DominanceResult",
    "EpistemicStatus",
    "EthicalEvaluator",
    "EthicalExperiment",
    "EthicalExperimentResult",
    "EvaluationReport",
    "EvidenceItem",
    "EvidenceSet",
    "ExperimentSummary",
    "JustificationResult",
    "LanguageAct",
    "LanguageAnalysis",
    "LanguageContext",
    "LanguageEthicsProfile",
    "LanguageMedium",
    "ManipulationFinding",
    "MoralAgent",
    "PolicyMode",
    "PolicyProfile",
    "Question",
    "QuestionCategory",
    "QuestionPriority",
    "QuestionSet",
    "ReasoningTrace",
    "ReversibilityProfile",
    "Rule",
    "RuleEngine",
    "RuleRegistry",
    "RuleResult",
    "RuleResultStatus",
    "RuleSeverity",
    "ScenarioTemplate",
    "SourceType",
    "TemporalConsequenceReport",
    "TemporalPhase",
    "TemporalProfile",
    "TemporalProjection",
    "TemporalProjectionResult",
    "TimeHorizon",
    "TradeoffAnalysis",
    "UncertaintyLevel",
    "Verdict",
    "agent_can_bear_duties",
    "analyse_alternatives",
    "analyze_language",
    "assess_consequences",
    "compare",
    "assess_agency",
    "assess_consent",
    "build_case_from_answers",
    "completeness_report",
    "default_registry",
    "detect_manipulation",
    "detect_missing_critical_data",
    "evaluate_coercion_justification",
    "generate_questions",
    "get_policy",
    "get_template",
    "list_templates",
    "project_temporal",
    "recommended_next_questions",
    "score_constructive_language",
    "score_cumulative_coercion",
    "score_language_ethics",
    "score_linguistic_coercion",
    "score_reversibility",
    "wizard_prompts",
    "__version__",
]
